config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "homebrews#index"

  resources :users, only: [:index, :show] do
    resources :friendships, only: :create
  end

  resources :friendships, only: :destroy

  resources :homebrews, only: [:index, :show, :new, :create] do
    resources :reviews, only: :create
  end

  namespace :api do
    api_version(
      :module => "V1",
      :header => {:name => "Accept",
      :value => "application/vnd.mycompany.com; version=1"},
      :defaults => {:format => :json},
      default: true
    ) do
      resources :homebrews, only: [:index, :show, :create, :update]
      resources :users, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  paginates_per 20

  has_many :homebrews,
    foreign_key: :brewer_id,
    dependent: :destroy
  has_many :friendships,
    dependent: :destroy
  has_many :inverse_friendships,
    class_name: "Friendship",
    foreign_key: :friend_id,
    dependent: :destroy
  has_many :friends,
    through: :friendships
  has_many :inverse_friends,
    through: :inverse_friendships,
    source: :user
  has_many :api_keys,
    dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  after_create :create_api_key

  def full_name
    "#{first_name} #{last_name}"
  end

  def can_friend?(user)
    self != user && !friends_with?(user)
  end

  def friends_with?(user)
    !friendship_for(user).nil?
  end

  def friendship_for(user)
    friendships.find_by(friend: user) ||
      inverse_friendships.find_by(user: user)
  end

  def all_friends
    friends_list = friends + inverse_friends
    friends_list.sort_by { |friend| [friend.last_name, friend.first_name] }
  end

  def can_review?(homebrew)
    (brewed?(homebrew) || friends_with?(homebrew.brewer)) &&
      !reviewed?(homebrew)
  end

  def reviewed?(homebrew)
    homebrew.reviews.persisted.any? { |review| review.reviewer == self }
  end

  def brewed?(homebrew)
    homebrew.brewer == self
  end

  def api_key
    api_keys.where("expires_at > ?", Time.now).first || api_keys.create
  end

  private

  def create_api_key
    api_keys.create
  end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order(:last_name, :first_name).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<h3>All Users</h3>

<div>
  <% @users.each do |user| %>
    <div>
      <%= link_to user.full_name, user_path(user) %>
      <% if user_signed_in? && current_user.can_friend?(user) %>
        <%= button_to "Add friend", user_friendships_path(user) %>
      <% elsif user_signed_in? && current_user.friends_with?(user) %>
        <%= button_to "Remove friend", friendship_path(current_user.friendship_for(user)), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @users %>

app/views/users/show.html.erb
<h3><%= @user.full_name %></h3>

<% if user_signed_in? %>
  <div>
    <% if current_user.can_friend?(@user) %>
      <%= button_to "Add friend", user_friendships_path(@user) %>
    <% elsif user_signed_in? && current_user.friends_with?(@user) %>
      <%= button_to "Remove friend", friendship_path(current_user.friendship_for(@user)), method: :delete %>
    <% end %>
  </div>
<% end %>

<div>
  <% if @user.homebrews.empty? %>
    <%= "#{@user.first_name} hasn't added any homebrews yet." %>
  <% else %>
    <%= "#{@user.first_name}'s homebrews:" %>
    <ul>
      <% @user.homebrews.each do |brew| %>
        <li><%= link_to "#{brew.name} (#{brew.date_brewed})", homebrew_path(brew) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div>
  <% if @user.all_friends.empty? %>
    <%= "#{@user.first_name} hasn't made any friends yet." %>
  <% else %>
    <%= "#{@user.first_name}'s friends:" %>
    <ul>
      <% @user.all_friends.each do |friend| %>
        <li><%= link_to friend.full_name, user_path(friend) %></li>
      <% end %>
    </ul>
  <% end %>
</div>