config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "homebrews#index"

  resources :users, only: [:index, :show] do
    resources :friendships, only: :create
  end

  resources :friendships, only: :destroy

  resources :homebrews, only: [:index, :show, :new, :create] do
    resources :reviews, only: :create
  end

  namespace :api do
    api_version(
      :module => "V1",
      :header => {:name => "Accept",
      :value => "application/vnd.mycompany.com; version=1"},
      :defaults => {:format => :json},
      default: true
    ) do
      resources :homebrews, only: [:index, :show, :create, :update]
      resources :users, only: [:index, :show]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

  <ul id="nav">
    <li><%= link_to "All homebrews", homebrews_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Add a homebrew", new_homebrew_path %></li>
      <li><%= link_to "Browse users", users_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
  </ul>

  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>